name: Create Neon Twin

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
  DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
  PG_VERSION: '16'

jobs:
  dump-and-restore:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ACCOUNT_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Install PostgreSQL Client
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-client-${{ env.PG_VERSION }}

      - name: Verify PostgreSQL Client Installation
        run: |
          pg_dump --version
          pg_restore --version

      - name: Debug Connection String
        env:
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          echo "Connection string: ${PROD_DATABASE_URL}" | sed 's/:.*@/:***@/'

      - name: Test RDS Connection
        env:
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          psql "${PROD_DATABASE_URL}" -c '\l'

      - name: Dump from RDS
        env:
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          echo "Dumping data from RDS to file..."
          pg_dump "${PROD_DATABASE_URL}" -Fc -f "${{ github.workspace }}/prod-dump-file.dump"

      - name: Restore to Neon
        env:
          DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
        run: |
          echo "Restoring data to Neon..."
          pg_restore -d "${DEV_DATABASE_URL}" --clean --no-owner --no-acl --if-exists "${{ github.workspace }}/prod-dump-file.dump"

      - name: Cleanup
        run: |
          echo "Cleaning up dump file..."
          rm -f "${{ github.workspace }}/prod-dump-file.dump"
